#!/bin/bash

copyto() {
  base=$1
  dest=$2
  if [ -d $base ]
  then
    mkdir -p $dest
    cp -r $base/* $dest/
  else
    cp $base $dest
  fi
}

dotboot() {
  files=`ls -A files/ | sort`

  for file in $files; do
    printf "$file\n" >> .dotfiles
  done

  files=`grep -v -x -f .dotignore .dotfiles`

  for file in $files; do
    base=files/$file
    dest=~/$file
    copyto "$base" "$dest"
  done

  rm .dotfiles
}

dotignore() {
  cat >> .dotignore <<__IGNORE
$1
__IGNORE

  FILES="`cat .dotignore | uniq | sort`"

  > .dotignore

  for IGNORED in "$FILES"; do
    printf "%s\n" $IGNORED >> .dotignore
  done
}

dotsync() {
  git add .
  git commit -m "sync at `date`"
  git push origin master
}

dotgrab() {
  file=$1
  dest=files/$1
  base=~/$file
  copyto "$base" "$dest"
}

dotlist() {
  ls -Al files
}

case $1 in
'boot' )
  dotboot
  ;;
'ignore' )
  dotignore $2
  ;;
'sync' )
  dotsync
  ;;
'grab' )
  dotgrab $2
  ;;
'list' )
  dotlist
  ;;
* )
  echo "Usage: dot [boot|ignore]"
  ;;
esac
